# Generated by Django 5.0.6 on 2024-05-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extrait', models.FileField(upload_to='extraits', verbose_name='Extrait')),
                ('certificat', models.FileField(upload_to='certificats', verbose_name='Certificat')),
                ('photos', models.FileField(upload_to='photos/', verbose_name='Photos')),
                ('reçu', models.FileField(upload_to='recus', verbose_name='Reçu')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
    ]
